Object subclass: #CommunicatesService

"============================================================================================================"

CommunicatesService >> talkToGuard1_1 [
    Transcript show: 'Guard: Can I see your ID?'; cr
]

CommunicatesService >> talkToGuard1_2 [
    Transcript show: '(How do i answer?)'; cr
]

CommunicatesService >> talkToGuard1_3 [
    Transcript show: '   a. I don\''t have one.'; cr
]

CommunicatesService >> talkToGuard1_4 [
    Transcript show: 'Me: I don\''t have one.'; cr
]

CommunicatesService >> talkToGuard1_5 [
    Transcript show: 'Guard: Sorry soldier, but you are not allowed to pass.'; cr
]

CommunicatesService >> talkToGuard1_6 [
    Transcript show: '   b. Here it is.'; cr
]

CommunicatesService >> talkToGuard_HereItIs [
    Transcript show: 'Me: Here it is.'; cr
]

CommunicatesService >> talkToGuard1_8 [
    Transcript show: 'Guard: You may pass.'; cr
]

CommunicatesService >> talkToGuard_wayNorthAccessible [
    Transcript show: '<A way north is now accesible.>'; cr
]

CommunicatesService >> talkToGuard1_9 [
    Transcript show: 'Guard: Guten Tag, Herr Gollmer!'; cr
]

"============================================================================================================"

CommunicatesService >> talkToGuard2_1 [
    Transcript show: 'Guard: Control! To access the archive or the offices, show your pass or key!'; cr
]

CommunicatesService >> talkToGuard2_2 [
    Transcript show: '(How do I answer?)'; cr
]

CommunicatesService >> talkToGuard2_3 [
    Transcript show: '   a. I don\''t have a pass.'; cr
]

CommunicatesService >> talkToGuard2_4 [
    Transcript show: 'Me: I don\''t a pass.'; cr
]

CommunicatesService >> talkToGuard2_5 [
    Transcript show: 'Guard: Then you have no right to enter.'; cr
]

CommunicatesService >> talkToGuard2_6 [
    Transcript show: '   b) Here it is. (id)'; cr
]

CommunicatesService >> talkToGuard2_7 [
    Transcript show: 'Guard: That pass won\''t do here. You cannot pass.'; cr
]

CommunicatesService >> talkToGuard2_8 [
    Transcript show: '   c. Here it is. (mid-rank pass)'; cr
]

CommunicatesService >> talkToGuard2_9 [
    Transcript show: 'Guard: Very well, but you may only enter the Archives.'; cr
]

CommunicatesService >> talkToGuard2_10 [
    Transcript show: '   d. Here it is. (red key)'; cr
]

CommunicatesService >> talkToGuard2_11 [
    Transcript show: 'Guard: Very well, you may now enter the offices.'; cr
]

CommunicatesService >> talkToGuard2_wayWestAccessible [
    Transcript show: '<A way west is now accessible>'; cr
]

CommunicatesService >> talkToGuard2_12 [
    Transcript show: '   b. I\''m the waiter, I have beverages for the Fuhrer.'; cr
]

CommunicatesService >> talkToGuard2_13 [
    Transcript show: 'Me: I\''m the waiter, I have beverages for the Fuhrer.'; cr
]

CommunicatesService >> talkToGuard2_14 [
    Transcript show: 'Guard: Hmmm, alright. But be quick with it!'; cr
]

"============================================================================================================"

CommunicatesService >> talkToGuard3_1 [
    Transcript show: 'Guard3: I know nothing, man. Ask the other guard.'; cr
]

CommunicatesService >> talkToGuard3_2 [
    Transcript show: 'Guard3: Sheisse! You killed him, you bastard! Prepare to die!'; cr
]

CommunicatesService >> talkToGuard3_3 [
    Transcript show: '<Guard3 shot me in the stomach. Thankfully i had my bulletproof vest on.>'; cr
]

CommunicatesService >> talkToGuard3_4 [
    Transcript show: '(Choose acction)'; cr
]

CommunicatesService >> talkToGuard3_5 [
    Transcript show: '   a. Shoot the guard'; cr
]

CommunicatesService >> talkToGuard3_6 [
    Transcript show: '<I shot the guard.>'; cr
]

CommunicatesService >> talkToGuard3_7 [
    Transcript show: 'Me: Both guards down, means I can finally face my target.'; cr
]

CommunicatesService >> talkToGuard3_8 [
    Transcript show: 'Me: One bullet left. Good God lend me the strength.'; cr
]

CommunicatesService >> talkToGuard3_9 [
    Transcript show: '<Guard3 shot me in the stomach. I am heavily wounded.>'; cr
]

CommunicatesService >> talkToGuard_wakeUpInMedbay [
    Transcript show: '<I wake up in the Medic Bay>'; cr
]

CommunicatesService >> talkToGuard_needVest [
    Transcript show: 'Me: Damn! I guess firepower alone isn\''t enough. I need some protection. I heard that the bulletproof vests are sold in the armory...'; cr
]

CommunicatesService >> talkToGuard3_10 [
    Transcript show: 'Guard3: Absolutely not! I''ll pass it to him. What do you have? Show me.'; cr
]

CommunicatesService >> talkToGuard3_11 [
    Transcript show: '(How do I answer?)'; cr
]

CommunicatesService >> talkToGuard3_12 [
    Transcript show: '   a. Apple juice, here you go.'; cr
]

CommunicatesService >> talkToGuard3_13 [
    Transcript show: 'Me: Apple juice, here you go.'; cr
]

CommunicatesService >> talkToGuard3_14 [
    Transcript show: 'Guard3: Our Fuehrer''s favorite, he will be pleased.'; cr
]

CommunicatesService >> talkToGuard3_15 [
    Transcript show: '<Guard passed the juice inside and returned>'; cr
]

CommunicatesService >> talkToGuard3_16 [
    Transcript show: '<A loud cough can be heard from Fuhrers'' quartes>'; cr
]

CommunicatesService >> talkToGuard3_17 [
    Transcript show: 'Guard3: We should check on Fuerher. I hope he''s alright.'; cr
]

CommunicatesService >> talkToGuard3_18 [
    Transcript show: '<Guard3 and Guard4 enter Fuerher''s quarters>'; cr
]

CommunicatesService >> talkToGuard3_19 [
    Transcript show: 'Me: Oh crap. They will find out what I''ve done.'; cr
]

CommunicatesService >> talkToGuard3_20 [
    Transcript show: 'Me: I HAVE TO RUN FOR MY LIFE'; cr
]

CommunicatesService >> talkToGuard3_21 [
    Transcript show: '<An exit through the food storage is now accessible>'; cr
]

CommunicatesService >> talkToGuard3_22 [
    Transcript show: '   a. Orange juice, perfect for Fuhrer.'; cr
]

CommunicatesService >> talkToGuard3_23 [
    Transcript show: 'Me: Orange juice, perfect for Fuhrer.'; cr
]

CommunicatesService >> talkToGuard3_24 [
    Transcript show: 'Guard4: He hates oranges. Don''t you know it?'; cr
]

CommunicatesService >> talkToGuard3_25 [
    Transcript show: '<Guard passed the juice inside and returned>'; cr
]

CommunicatesService >> talkToGuard3_26 [
    Transcript show: 'Me: *whispers* Well, there goes my poison. I hope he likes oranges. (he does not)'; cr
]

CommunicatesService >> talkToGuard3_27 [
    Transcript show: '   a. Multivitamina juice, Tymbark trademark.'; cr
]

CommunicatesService >> talkToGuard3_28 [
    Transcript show: 'Me: Multivitamina juice, Tymbark trademark.'; cr
]

CommunicatesService >> talkToGuard3_29 [
    Transcript show: 'Guard3: Polish apple''s... Shame they have been corrupted by impure tropical fruits...'; cr
]

CommunicatesService >> talkToGuard3_30 [
    Transcript show: '<Guard passed the juice inside and returned>'; cr
]

CommunicatesService >> talkToGuard3_31 [
    Transcript show: 'Me: *whispers* Well, there goes my poison. I hope he likes multivitamina. (he does not)'; cr
]

"============================================================================================================"

CommunicatesService >> talkToGuard4_1 [
    Transcript show: 'Guard4: Halt! None shall enter Furher''s quarters! What do you want?'; cr
]

CommunicatesService >> talkToGuard4_2 [
    Transcript show: '(How do I answer?)'; cr
]

CommunicatesService >> talkToGuard4_3 [
    Transcript show: '   a. I''ll be on my way.'; cr
]

CommunicatesService >> talkToGuard4_4 [
    Transcript show: 'Me: I''ll be on my way.'; cr
]

CommunicatesService >> talkToGuard4_5 [
    Transcript show: 'Guard4: As you should... Begone!'; cr
]

CommunicatesService >> talkToGuard4_6 [
    Transcript show: '   b. I have beverages for Fuehrer. Can I deliver them to him?'; cr
]

CommunicatesService >> talkToGuard4_7 [
    Transcript show: 'Me: I have beverages for Fuerher. Can I deliver them to him?'; cr
]

CommunicatesService >> talkToGuard4_8 [
    Transcript show: 'Guard4: Sheisse! You killed him, you bastard! Prepare to die!'; cr
]

CommunicatesService >> talkToGuard4_9 [
    Transcript show: '<Guard4 shot me in the stomach. Thankfully i had my bulletproof vest on.>'; cr
]

CommunicatesService >> talkToGuard4_10 [
    Transcript show: '(Choose action)'; cr
]

CommunicatesService >> talkToGuard4_11 [
    Transcript show: '   a. Shoot the guard'; cr
]

CommunicatesService >> talkToGuard4_12 [
    Transcript show: '<I shot the guard.>'; cr
]

CommunicatesService >> talkToGuard4_13 [
    Transcript show: 'Me: Both guards down, means I can finally face my target.'; cr
]

CommunicatesService >> talkToGuard4_15 [
    Transcript show: 'Me: One bullet left. Good God lend me thy strength.'; cr
]

CommunicatesService >> talkToGuard4_16 [
    Transcript show: '<Guard4 shot me in the stomach. I am heavily wounded.>'; cr
]
