Object subclass: #CommunicatesService

CommunicatesService >> talkToBandit_1 [
    Transcript show: 'Bandit: Hey boy, are you lost? You have found yourself in the wrong place at the wrong time.'; cr
]

CommunicatesService >> talkToBandit_2 [
    Transcript show: '(How do I answer?)'; cr
]

CommunicatesService >> talkToBandit_3 [
    Transcript show: '   a. Who are you?'; cr
]

CommunicatesService >> talkToBandit_4 [
    Transcript show: 'Me: Who are you?'; cr
]

CommunicatesService >> talkToBandit_5 [
    Transcript show: 'Bandit: I am your last memory. Say goodbye to life!'; cr
]

CommunicatesService >> talkToBandit_6 [
    Transcript show: '<A bandit struck me in the head>'; cr
]

CommunicatesService >> talkToBandit_7 [
    Transcript show: 'Thank Lord I had my helmet on. Would have been a pity, if i didn''t.'; cr
]

CommunicatesService >> talkToBandit_8 [
    Transcript show: '(Choose action)'; cr
]

CommunicatesService >> talkToBandit_9 [
    Transcript show: '   a. Strike the bandit with my baton'; cr
]

CommunicatesService >> talkToBandit_10 [
    Transcript show: '<I struck the bandit with my own baton>'; cr
]

CommunicatesService >> talkToBandit_11 [
    Transcript show: 'Me: The bandit looks unconscious. I''d better tie him up'; cr
]

CommunicatesService >> talkToBandit_12 [
    Transcript show: '<I tied up the bandit. He can cause no more harm>'; cr
]

CommunicatesService >> talkToBandit_13 [
    Transcript show: '   a. Punch the bandit in the face'; cr
]

CommunicatesService >> talkToBandit_14 [
    Transcript show: '<I punched the bandit>'; cr
]

CommunicatesService >> talkToBandit_15 [
    Transcript show: 'Bandit: UGH! That hurt! But your weak fists are no match for the baton of mine. Yield to my strenght!'; cr
]

CommunicatesService >> talkToBandit_16 [
    Transcript show: '<The bandit struck me in the head again, rendering me unconscious>'; cr
]

CommunicatesService >> talkToBandit_17 [
    Transcript show: '<I wake up in the Medic Bay>'; cr
]

CommunicatesService >> talkToBandit_18 [
    Transcript show: 'Me: Damn! I guess I need a weapon to best that guy. Maybe a baton will do?'; cr
]

CommunicatesService >> talkToBandit_19 [
    Transcript show: '<The bandit''s strike rendered me unconscious>'; cr
]

CommunicatesService >> talkToBandit_20 [
    Transcript show: 'Me: Damn! I guess having a baton isn''t enough. I need some protection. Myabe a helmet will do?'; cr
]

CommunicatesService >> talkToBandit_21 [
    Transcript show: 'Me: Damn! He easliy overpowered me! I need a weapon to match him. Maybe a baton will do?'; cr
]

"============================================================================================================"

CommunicatesService >> talkToChef_1 [
    Transcript show: 'Chef: Hello, my friend! Unfortunately, I need to see your pass to let you in.'; cr
]

CommunicatesService >> talkToChef_2 [
    Transcript show: '(How do I answer?)'; cr
]

CommunicatesService >> talkToChef_3 [
    Transcript show: '   a. I don''t have one.'; cr
]

CommunicatesService >> talkToChef_4 [
    Transcript show: 'Me: I don''t have one.'; cr
]

CommunicatesService >> talkToChef_5 [
    Transcript show: 'Chef: Oh, that''s most unfortunate. Come back when you have a pass.'; cr
]

CommunicatesService >> talkToChef_6 [
    Transcript show: '   b. Here it is. (id)'; cr
]

CommunicatesService >> talkToChef_7 [
    Transcript show: 'Chef: That pass won''t do here. You need at least a mid-rank pass.'; cr
]

CommunicatesService >> talkToChef_8 [
    Transcript show: '   c. Here it is. (mid-rank pass)'; cr
]

CommunicatesService >> talkToChef_9 [
    Transcript show: 'Me: Here it is.'; cr
]

CommunicatesService >> talkToChef_10 [
    Transcript show: 'Chef: You may pass.'; cr
]

CommunicatesService >> talkToChef_wayEastAcessible [
    Transcript show: '<A way east is now accessible.>'; cr
]

CommunicatesService >> talkToChef_10 [
    Transcript show: 'Chef: I cannot talk now, I am busy.'; cr
]

"============================================================================================================"


CommunicatesService >> talkToFuhrer_1 [
    Transcript show: 'Adolf Hitler: Who the hell are you? I don''t know you. How did you get in here?'; cr
]

CommunicatesService >> talkToFuhrer_2 [
    Transcript show: '(How do I answer?)'; cr
]

CommunicatesService >> talkToFuhrer_3 [
    Transcript show: '   a. I am the bringer of peace. A hero even. Die scum!'; cr
]

CommunicatesService >> talkToFuhrer_4 [
    Transcript show: '   b. I am not one of your soldier. I am an American spy and came here to kill you.'; cr
]

CommunicatesService >> talkToFuhrer_5 [
    Transcript show: '   c. I am here to end this war, by putting a bullet in your skull.'; cr
]

CommunicatesService >> talkToFuhrer_6 [
    Transcript show: 'Me: I am the bringer of peace. A hero even. Die scum!'; cr
]

CommunicatesService >> talkToFuhrer_7 [
    Transcript show: 'Me: I am not one of your soldier. I am an American spy and came here to kill you.'; cr
]

CommunicatesService >> talkToFuhrer_8 [
    Transcript show: 'Me: I am here to end this war, by putting a bullet in your skull.'; cr
]

CommunicatesService >> talkToFuhrer_9 [
    Transcript show: 'Adolf Hitler: Oh NEIN! Why would you do such a thing? Please do not kill me!'; cr
]

CommunicatesService >> talkToFuhrer_10 [
    Transcript show: 'Me: Too late, you monster. Now, pay for your sins!'; cr
]

CommunicatesService >> talkToFuhrer_11 [
    Transcript show: '(Choose action)'; cr
]

CommunicatesService >> talkToFuhrer_12 [
    Transcript show: '   a. Shoot Hitler'; cr
]

CommunicatesService >> talkToFuhrer_13 [
    Transcript show: '<I shot Adolf Hitler dead>'; cr
]


"============================================================================================================"

CommunicatesService >> talkToGuard1_1 [
    Transcript show: 'Guard: Can I see your ID?'; cr
]

CommunicatesService >> talkToGuard1_2 [
    Transcript show: '(How do i answer?)'; cr
]

CommunicatesService >> talkToGuard1_3 [
    Transcript show: '   a. I don\''t have one.'; cr
]

CommunicatesService >> talkToGuard1_4 [
    Transcript show: 'Me: I don\''t have one.'; cr
]

CommunicatesService >> talkToGuard1_5 [
    Transcript show: 'Guard: Sorry soldier, but you are not allowed to pass.'; cr
]

CommunicatesService >> talkToGuard1_6 [
    Transcript show: '   b. Here it is.'; cr
]

CommunicatesService >> talkToGuard_HereItIs [
    Transcript show: 'Me: Here it is.'; cr
]

CommunicatesService >> talkToGuard1_8 [
    Transcript show: 'Guard: You may pass.'; cr
]

CommunicatesService >> talkToGuard_wayNorthAccessible [
    Transcript show: '<A way north is now accesible.>'; cr
]

"============================================================================================================"

CommunicatesService >> talkToGuard2_1 [
    Transcript show: 'Guard: Control! To access the archive or the offices, show your pass or key!'; cr
]

CommunicatesService >> talkToGuard2_2 [
    Transcript show: '(How do I answer?)'; cr
]

CommunicatesService >> talkToGuard2_3 [
    Transcript show: '   a. I don\''t have a pass.'; cr
]

CommunicatesService >> talkToGuard2_4 [
    Transcript show: 'Me: I don\''t a pass.'; cr
]

CommunicatesService >> talkToGuard2_5 [
    Transcript show: 'Guard: Then you have no right to enter.'; cr
]

CommunicatesService >> talkToGuard2_6 [
    Transcript show: '   b) Here it is. (id)'; cr
]

CommunicatesService >> talkToGuard2_7 [
    Transcript show: 'Guard: That pass won\''t do here. You cannot pass.'; cr
]

CommunicatesService >> talkToGuard2_8 [
    Transcript show: '   c. Here it is. (mid-rank pass)'; cr
]

CommunicatesService >> talkToGuard2_9 [
    Transcript show: 'Guard: Very well, but you may only enter the Archives.'; cr
]

CommunicatesService >> talkToGuard2_10 [
    Transcript show: '   d. Here it is. (red key)'; cr
]

CommunicatesService >> talkToGuard2_11 [
    Transcript show: 'Guard: Very well, you may now enter the offices.'; cr
]

CommunicatesService >> talkToGuard2_wayWestAccessible [
    Transcript show: '<A way west is now accessible>'; cr
]

CommunicatesService >> talkToGuard2_12 [
    Transcript show: '   b. I\''m the waiter, I have beverages for the Fuhrer.'; cr
]

CommunicatesService >> talkToGuard2_13 [
    Transcript show: 'Me: I\''m the waiter, I have beverages for the Fuhrer.'; cr
]

CommunicatesService >> talkToGuard2_14 [
    Transcript show: 'Guard: Hmmm, alright. But be quick with it!'; cr
]

CommunicatesService >> talkToGuard2_15 [
    Transcript show: 'Me: Here it is.'; cr
]

"============================================================================================================"

CommunicatesService >> talkToGuard3_1 [
    Transcript show: 'Guard3: I know nothing, man. Ask the other guard.'; cr
]

CommunicatesService >> talkToGuard3_2 [
    Transcript show: 'Guard3: Sheisse! You killed him, you bastard! Prepare to die!'; cr
]

CommunicatesService >> talkToGuard3_3 [
    Transcript show: '<Guard3 shot me in the stomach. Thankfully i had my bulletproof vest on.>'; cr
]

CommunicatesService >> talkToGuard3_4 [
    Transcript show: '(Choose acction)'; cr
]

CommunicatesService >> talkToGuard3_5 [
    Transcript show: '   a. Shoot the guard'; cr
]

CommunicatesService >> talkToGuard3_6 [
    Transcript show: '<I shot the guard.>'; cr
]

CommunicatesService >> talkToGuard3_7 [
    Transcript show: 'Me: Both guards down, means I can finally face my target.'; cr
]

CommunicatesService >> talkToGuard3_8 [
    Transcript show: 'Me: One bullet left. Good God lend me the strength.'; cr
]

CommunicatesService >> talkToGuard3_9 [
    Transcript show: '<Guard3 shot me in the stomach. I am heavily wounded.>'; cr
]

CommunicatesService >> talkToGuard_wakeUpInMedbay [
    Transcript show: '<I wake up in the Medic Bay>'; cr
]

CommunicatesService >> talkToGuard_needVest [
    Transcript show: 'Me: Damn! I guess firepower alone isn\''t enough. I need some protection. I heard that the bulletproof vests are sold in the armory...'; cr
]

CommunicatesService >> talkToGuard3_10 [
    Transcript show: 'Guard3: Absolutely not! I''ll pass it to him. What do you have? Show me.'; cr
]

CommunicatesService >> talkToGuard3_11 [
    Transcript show: '(How do I answer?)'; cr
]

CommunicatesService >> talkToGuard3_12 [
    Transcript show: '   a. Apple juice, here you go.'; cr
]

CommunicatesService >> talkToGuard3_13 [
    Transcript show: 'Me: Apple juice, here you go.'; cr
]

CommunicatesService >> talkToGuard3_14 [
    Transcript show: 'Guard3: Our Fuehrer''s favorite, he will be pleased.'; cr
]

CommunicatesService >> talkToGuard3_15 [
    Transcript show: '<Guard passed the juice inside and returned>'; cr
]

CommunicatesService >> talkToGuard3_16 [
    Transcript show: '<A loud cough can be heard from Fuhrers'' quartes>'; cr
]

CommunicatesService >> talkToGuard3_17 [
    Transcript show: 'Guard3: We should check on Fuerher. I hope he''s alright.'; cr
]

CommunicatesService >> talkToGuard3_18 [
    Transcript show: '<Guard3 and Guard4 enter Fuerher''s quarters>'; cr
]

CommunicatesService >> talkToGuard3_19 [
    Transcript show: 'Me: Oh crap. They will find out what I''ve done.'; cr
]

CommunicatesService >> talkToGuard3_20 [
    Transcript show: 'Me: I HAVE TO RUN FOR MY LIFE'; cr
]

CommunicatesService >> talkToGuard3_21 [
    Transcript show: '<An exit through the food storage is now accessible>'; cr
]

CommunicatesService >> talkToGuard3_22 [
    Transcript show: '   a. Orange juice, perfect for Fuhrer.'; cr
]

CommunicatesService >> talkToGuard3_23 [
    Transcript show: 'Me: Orange juice, perfect for Fuhrer.'; cr
]

CommunicatesService >> talkToGuard3_24 [
    Transcript show: 'Guard4: He hates oranges. Don''t you know it?'; cr
]

CommunicatesService >> talkToGuard3_25 [
    Transcript show: '<Guard passed the juice inside and returned>'; cr
]

CommunicatesService >> talkToGuard3_26 [
    Transcript show: 'Me: *whispers* Well, there goes my poison. I hope he likes oranges. (he does not)'; cr
]

CommunicatesService >> talkToGuard3_27 [
    Transcript show: '   a. Multivitamina juice, Tymbark trademark.'; cr
]

CommunicatesService >> talkToGuard3_28 [
    Transcript show: 'Me: Multivitamina juice, Tymbark trademark.'; cr
]

CommunicatesService >> talkToGuard3_29 [
    Transcript show: 'Guard3: Polish apple''s... Shame they have been corrupted by impure tropical fruits...'; cr
]

CommunicatesService >> talkToGuard3_30 [
    Transcript show: '<Guard passed the juice inside and returned>'; cr
]

CommunicatesService >> talkToGuard3_31 [
    Transcript show: 'Me: *whispers* Well, there goes my poison. I hope he likes multivitamina. (he does not)'; cr
]

"============================================================================================================"

CommunicatesService >> talkToGuard4_1 [
    Transcript show: 'Guard4: Halt! None shall enter Furher''s quarters! What do you want?'; cr
]

CommunicatesService >> talkToGuard4_2 [
    Transcript show: '(How do I answer?)'; cr
]

CommunicatesService >> talkToGuard4_3 [
    Transcript show: '   a. I''ll be on my way.'; cr
]

CommunicatesService >> talkToGuard4_4 [
    Transcript show: 'Me: I''ll be on my way.'; cr
]

CommunicatesService >> talkToGuard4_5 [
    Transcript show: 'Guard4: As you should... Begone!'; cr
]

CommunicatesService >> talkToGuard4_6 [
    Transcript show: '   b. I have beverages for Fuehrer. Can I deliver them to him?'; cr
]

CommunicatesService >> talkToGuard4_7 [
    Transcript show: 'Me: I have beverages for Fuerher. Can I deliver them to him?'; cr
]

CommunicatesService >> talkToGuard4_8 [
    Transcript show: 'Guard4: Sheisse! You killed him, you bastard! Prepare to die!'; cr
]

CommunicatesService >> talkToGuard4_9 [
    Transcript show: '<Guard4 shot me in the stomach. Thankfully i had my bulletproof vest on.>'; cr
]

CommunicatesService >> talkToGuard4_10 [
    Transcript show: '(Choose action)'; cr
]

CommunicatesService >> talkToGuard4_11 [
    Transcript show: '   a. Shoot the guard'; cr
]

CommunicatesService >> talkToGuard4_12 [
    Transcript show: '<I shot the guard.>'; cr
]

CommunicatesService >> talkToGuard4_13 [
    Transcript show: 'Me: Both guards down, means I can finally face my target.'; cr
]

CommunicatesService >> talkToGuard4_15 [
    Transcript show: 'Me: One bullet left. Good God lend me thy strength.'; cr
]

CommunicatesService >> talkToGuard4_16 [
    Transcript show: '<Guard4 shot me in the stomach. I am heavily wounded.>'; cr
]

"============================================================================================================"

CommunicatesService >> talkToYourself_1 [
    Transcript show: '<I cannot talk to a corpse, now can I?>'; cr
]

CommunicatesService >> talkToYourself_2 [
    Transcript show: '<I pulled the lever>'; cr
]

CommunicatesService >> talkToYourself_3 [
    Transcript show: '<I hear rumbling. I think this might have opened a secret door>'; cr
]

CommunicatesService >> talkToYourself_4 [
    Transcript show: '<I already pulled this lever>'; cr
]

CommunicatesService >> talkToYourself_5 [
    Transcript show: '<I cannot interact with this>'; cr
]

CommunicatesService >> talkToYourself_6 [
    Transcript show: 'You killed Hitler. (shot him in the heart)'; cr
]

CommunicatesService >> talkToYourself_7 [
    Transcript show: 'You killed Hitler. (he died of poisoning)'; cr
]

CommunicatesService >> talkToYourself_8 [
    Transcript show: 'Thanks!'; cr
]

CommunicatesService >> talkToYourself_9 [
    Transcript show: 'Oh and for playing the game we thank you as well!'; cr
]

CommunicatesService >> talkToYourself_10 [
    Transcript show: '<GAME OVER>'; cr
]

CommunicatesService >> talkToYourself_11 [
    Transcript show: '<type ''quit'' to quit>'; cr
]

"============================================================================================================"

CommunicatesService >> talkToSalesman_1 [
    Transcript show: 'Salesman: Greetings, soldier. What are you looking for?'; cr
]

CommunicatesService >> talkToSalesman_2 [
    Transcript show: '(How do i answer?)'; cr
]

CommunicatesService >> talkToSalesman_3 [
    Transcript show: '   b. A bulletproof vest'; cr
]

CommunicatesService >> talkToSalesman_4 [
    Transcript show: '   c. I am not looking for anything'; cr
]

CommunicatesService >> talkToSalesman_5 [
    Transcript show: 'Me: A gun'; cr
]

CommunicatesService >> talkToSalesman_6 [
    Transcript show: 'Me: A bulletproof vest'; cr
]

CommunicatesService >> talkToSalesman_7 [
    Transcript show: 'Me: I am not looking for anything'; cr
]

CommunicatesService >> talkToSalesman_8 [
    Transcript show: 'Salesman: Ho ho, this is a premium product. Give me amber, and I''ll hand you this gun.'; cr
]

CommunicatesService >> talkToSalesman_9 [
    Transcript show: '   a) It''s a deal!'; cr
]

CommunicatesService >> talkToSalesman_10 [
    Transcript show: '   b) I changed my mind.'; cr
]

CommunicatesService >> talkToSalesman_11 [
    Transcript show: 'Me: It''s a deal!'; cr
]

CommunicatesService >> talkToSalesman_12 [
    Transcript show: 'Me: Only three bullets. I have to make each one count.'; cr
]

CommunicatesService >> talkToSalesman_13 [
    Transcript show: 'Me: I changed my mind.'; cr
]

CommunicatesService >> talkToSalesman_14 [
    Transcript show: '   a. I don''t have an amber.'; cr
]

CommunicatesService >> talkToSalesman_15 [
    Transcript show: 'Me: I don''t have an amber'; cr
]

CommunicatesService >> talkToSalesman_16 [
    Transcript show: 'Salesman: This amazing bulletproof vest can be yours for only 1000 Reichmarks. A bargain!'; cr
]

CommunicatesService >> talkToSalesman_17 [
    Transcript show: '<I just purchased a bulletproof vest for a 1000 Reichmarks>'; cr
]

CommunicatesService >> talkToSalesman_18 [
    Transcript show: '   a. I don''t have that much money.'; cr
]

CommunicatesService >> talkToSalesman_19 [
    Transcript show: 'Me: I don''t have that much money.'; cr
]

CommunicatesService >> talkToSalesman_20 [
    Transcript show: 'Salesman: Here you go, hope it serves you well.'; cr
]

CommunicatesService >> talkToSalesman_21 [
    Transcript show: 'Salesman: I''m not running a charity, come back with amber!'; cr
]

CommunicatesService >> talkToSalesman_22 [
    Transcript show: 'Salesman: I''m not running a charity, come back with money!'; cr
]

"============================================================================================================"

CommunicatesService >> talkToSoldier_1 [
    Transcript show: 'Soldier: Hey, how''s it going? Do you want to play cards?'; cr
]

CommunicatesService >> talkToSoldier_2 [
    Transcript show: '(How do i answer?)'; cr
]

CommunicatesService >> talkToSoldier_3 [
    Transcript show: '   a. No'; cr
]

CommunicatesService >> talkToSoldier_4 [
    Transcript show: '   b. Yes'; cr
]

CommunicatesService >> talkToSoldier_5 [
    Transcript show: 'Me: No, thanks.'; cr
]

CommunicatesService >> talkToSoldier_6 [
    Transcript show: 'Soldier: In that case, we''ll play another time.'; cr
]

CommunicatesService >> talkToSoldier_7 [
    Transcript show: 'Me: Yes, I am the master of card games!'; cr
]

CommunicatesService >> talkToSoldier_8 [
    Transcript show: 'Soldier: That''s great! In that case, you put up your umbrella, and I''ll put up my helmet. May the best one win.'; cr
]

CommunicatesService >> talkToSoldier_9 [
    Transcript show: '<I played cards with soldier>'; cr
]

CommunicatesService >> talkToSoldier_10 [
    Transcript show: 'Soldier: Damn, you definitely cheated. Here''s the helmet, now get lost!'; cr
]

CommunicatesService >> talkToSoldier_11 [
    Transcript show: '<I just won a helmet!>'; cr
]

CommunicatesService >> talkToSoldier_12 [
    Transcript show: 'Soldier: Oh, wait. It''s you again! I won''t play with a cheater!'; cr
]

CommunicatesService >> talkToSoldier_13 [
    Transcript show: 'Soldier: This is great! But do you even have anything to put up? I think not. You must have something in order to play. Anything will do, even an umbrella.'; cr
]

"============================================================================================================"

CommunicatesService >> talkToWaiter_1 [
    Transcript show: 'Waiter: Good day to you sir!'; cr
]

"============================================================================================================"

CommunicatesService >> hitlerShot [
    Transcript show: 'You killed Hitler. (shot him in the heart)'; cr
]

CommunicatesService >> hitlerPoisoned [
    Transcript show: 'You killed Hitler. (he died of poisoning)'; cr
]

CommunicatesService >> thanks [
    Transcript show: 'Thanks!'; cr
]

CommunicatesService >> hitlerPoisoned [
    Transcript show: 'Oh and for playing the game we thank you as well!'; cr
]

CommunicatesService >> hitlerPoisoned [
    Transcript show: '<GAME OVER>'; cr
]

CommunicatesService >> hitlerPoisoned [
    Transcript show: '<type ''quit'' to quit>'; cr
]

"============================================================================================================"

CommunicatesService >> authorized [
    Transcript show: 'Guard: Guten Tag, Herr Gollmer!'; cr
]